# Generated by Django 4.2.3 on 2023-07-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
    ]
