# Generated by Django 4.2.3 on 2023-07-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_face_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
