# Generated by Django 4.2.3 on 2023-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='user'),
            preserve_default=False,
        ),
    ]
