# Generated by Django 4.2.3 on 2023-09-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
