# Generated by Django 4.2.3 on 2023-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_card_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
