# Generated by Django 4.2.3 on 2023-07-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_card_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='card'),
        ),
    ]
