# Generated by Django 4.2.3 on 2023-07-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='serial_num',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
