# Generated by Django 4.2.3 on 2023-07-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_membership_serial_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.membership')),
            ],
        ),
    ]
