# Generated by Django 4.2.3 on 2023-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_membership_point_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='cur_total',
            field=models.IntegerField(default=0),
        ),
    ]
