# Generated by Django 4.2.3 on 2023-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_history_cur_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='image',
            field=models.ImageField(default=1, upload_to='membership'),
            preserve_default=False,
        ),
    ]
