# Generated by Django 4.2.3 on 2023-07-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_temperature_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
