# Generated by Django 4.2.3 on 2023-07-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
