# Generated by Django 4.2.3 on 2023-07-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_temperature_size'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.size'),
        ),
        migrations.AlterField(
            model_name='option',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.temperature'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
