# Generated by Django 4.2.3 on 2023-07-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_option_size_alter_option_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_pack',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
