# Generated by Django 4.2.3 on 2023-07-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_temperature_size'),
        ('order', '0004_remove_option_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='menu',
        ),
        migrations.AddField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.menu'),
            preserve_default=False,
        ),
    ]
