# Generated by Django 4.2.3 on 2023-07-27 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_option_menu_option_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 27, 16, 51, 50, 82023)),
            preserve_default=False,
        ),
    ]
