# Generated by Django 4.2.3 on 2023-07-30 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_delete_favorite'),
        ('order', '0009_remove_order_brand_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffee.brand'),
            preserve_default=False,
        ),
    ]
