name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run commands on EC2
        run: |
          ssh -i /home/ubuntu/.ssh/id_rsa ubuntu@3.36.95.105 "echo hi"
