name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture : 'x64'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          ssh ubuntu@ip-172-31-2-138 'cd OKDK_APP_Backend && git pull && systemctl restart gunicorn'
