name: Automatic pull in EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on EC2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 내가 변수로 저장한 pem key
          host: ${{ secrets.HOST }} # 내가 변수로 저장한 ip
          username: ${{ secrets.USER }} # 내가 변수로 저장한 User
          script: |
            echo hi

