name: Automatic pull in EC2

on:
  push:
    branches:
      - develop

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{secrets.HOST}}
          USER_NAME: ${{secrets.USER}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          cd /home/${USER_NAME}/OKDK_APP_Backend
          git pull
          sudo systemctl restart gunicorn

